name: End-to-end Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress Tests ðŸ§ª
        uses: cypress-io/github-action@v6

      - name: HTML Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-linux
          path: cucumber-report.html
          if-no-files-found: ignore

  tests-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress Tests ðŸ§ª
        uses: cypress-io/github-action@v6

      - name: HTML Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report-windows
          path: cucumber-report.html
          if-no-files-found: ignore


  deploy:
    name: Deploy HTML Report to GitHub Pages
    needs: 
      - tests-linux
      - tests-windows
    runs-on: ubuntu-24.04
    if: always()

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: https://andre-min.github.io/curso-cypress-cucumber/

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      # Download Linux report
      - name: Download Linux Report
        uses: actions/download-artifact@v4
        with:
          name: test-report-linux
          path: temp/linux/

      # Download Windows report
      - name: Download Windows Report
        uses: actions/download-artifact@v4
        with:
          name: test-report-windows
          path: temp/windows/

      # Renomear e mover para raiz da publicaÃ§Ã£o
      - name: Move reports to root
        run: |
          mkdir site
          mv temp/linux/cucumber-report.html site/cucumber-linux.html
          mv temp/windows/cucumber-report.html site/cucumber-windows.html
          echo "Arquivos movidos e renomeados: "
          ls -R site

      # Publicar tudo que estiver na pasta site/
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
